import {AppProvider} from "@/components/AppContext";
import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "@/components/layout/Header";
import {Toaster} from "react-hot-toast";


const roboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ['400','500','700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${roboto.className} antialiased`}>
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
          <Toaster/>
          <Header />
          {children}
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
